apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: student-app
data:
  allowed-origins: "http://newcom679.net,https://newcom679.net,http://www.newcom679.net,https://www.newcom679.net,http://134.122.23.72,http://localhost:3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: student-app
data:
  api-url: "http://backend:8000/api"
