apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: student-app

resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - storage.yaml
  - redis.yaml
  - kafka.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: base
